#!/bin/bash

# Unfortunately for deb 11 we need to do this to packages that user libappindicator3-1

sudo su
dpkg-deb -x $1 unpack
dpkg-deb --control $1 unpack/DEBIAN
rm $1
sed -i 's/libappindicator/libayatana-appindicator/' ./unpack/DEBIAN/control
dpkg -b unpack $1
dpkg -i $1
