#!/bin/bash

CURRENT_CONNECTION=$(xrandr -q | grep "connected" | awk '/ connected/ {print $1}' | wc -l)
CHANGE() {
    xrandr --output "$1" --auto --scale 1.0x1.0 $(xrandr -q | grep "connected" | grep -v "\b$1" | awk '{print "--output", $1, "--off"}' | paste -sd ' ' -)
}


if [ $CURRENT_CONNECTION = 1 ]
then
	CHANGE "eDP-1"
	pactl set-card-profile 0 output:analog-stereo
	nitrogen --restore
else
	CHANGE "HDMI-2"
	pactl set-card-profile 0 output:hdmi-stereo-extra1
	nitrogen --restore
fi
